### ISSUE TITLE
LICENSE and minified files

### ISSUE THREAD

**Issue by amper5and** [DanielRuf/secrets.js-next#3]
If you're going to fork a project, rename it, and publish it without crediting the original developer, at least remember to change the name in the LICENSE file. 

Also, the minified js doesn't correspond to your full js code at this point.

**Comment by DanielRuf** [comment]
The files are still the same and your minified version does not include any header comments.

And why should I not give any credit to you?
It is already renamed and published under the new name.

So far there is no build task. But this is on my todo (webpack).

**Comment by DanielRuf** [comment]
Thanks for the hint about the LICENSE file. Will generate a new one and update it accordingly. It was late yesterday.

**Comment by amper5and** [comment]
I don't think you understood what I meant, because your reply doesn't make any sense as a response to my post.

**Comment by DanielRuf** [comment]
I did no changes to the js files so far. I just made a new release and started work on a build task.

**Comment by DanielRuf** [comment]
I just missed the change in the LICENSE file.

**Comment by amper5and** [comment]
Oh you DEFINITELY don't understand. 

https://www.npmjs.com/package/secrets.js-next

https://github.com/amper5and/secrets.js/compare/master...DanielRuf:master

**Comment by DanielRuf** [comment]
It's just the name of the repository. The file name does not matter so far. Also the repo name and packagename have to be different to release it on npmjs ;-)

I do not understand what the problem is. I just started work here and I did not yet commit the started work.

I'll push the updated license later.

**Comment by DanielRuf** [comment]
The next part is meant to desvribe the build task in the future and rewrites (ES6 ES next, webpack, node streams, ...).

**Comment by amper5and** [comment]
Are you serious?

Take a look at this fork to see how professionals attribute original developers. 

https://github.com/grempe/secrets.js

I'm done with this conversation. Good luck with your new project.
